[package]
name = "jevons-generative"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
jevons-core.workspace = true
jevons-diffusion.workspace = true

[dev-dependencies]
jevons-diffusion = { workspace = true, features = ["testing"] }

[lints]
workspace = true
