//! Selectors for a recorded element: XPath expressions that select it, and only it, in the
//! interface it was recorded in, most robust first.
//!
//! 1. Its automation id, unless the id looks generated per item (timestamps, long numbers).
//! 2. Its classes (one, then two together), which are the same in every language.
//! 3. A stable ancestor (by id or class) and its role and class below it.
//! 4. The text it or a descendant `Text` shows, which is what a script's argument would carry
//!    (`//TreeItem[.//Text[@name = $channel]]`).
//! 5. Its name, which is in the user's language.
//! 6. Its position from the window, as a last resort.
//!
//! Each candidate is checked against the recorded interface: it must select exactly the element.

use super::parse::ROLES;
use super::{Document, Node, Variables, XPath};
use crate::platform::{ContextInspector, UiElement};
use crate::recorded::{RecordedInspector, RecordedTree};
use serde::{Deserialize, Serialize};

/// One way to find a recorded element again.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct Candidate {
    pub xpath: String,
    /// `automation_id`, `class`, `anchored`, `text`, `name` or `path`.
    pub how: String,
    /// Whether it holds up when the user's language changes (no names in it).
    pub stable: bool,
    /// The literal text it matches, which a script could take as an argument instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

/// Text as an XPath literal, whatever quotes it holds.
pub fn literal(text: &str) -> String {
    if !text.contains('\'') {
        format!("'{text}'")
    } else if !text.contains('"') {
        format!("\"{text}\"")
    } else {
        let parts: Vec<String> = text.split('\'').map(|p| format!("'{p}'")).collect();
        format!("concat({})", parts.join(", \"'\", "))
    }
}

/// An element test: its role, or `*[@role=…]` for one outside the control types.
fn role_test(role: &str) -> String {
    if ROLES.contains(&role) {
        role.to_string()
    } else {
        format!("*[@role={}]", literal(role))
    }
}

/// An id that looks generated per item: long digit runs (timestamps) or long hexadecimal.
pub fn volatile(id: &str) -> bool {
    let longest_digits = id
        .split(|c: char| !c.is_ascii_digit())
        .map(str::len)
        .max()
        .unwrap_or(0);
    let hex = id.len() >= 16 && id.chars().all(|c| c.is_ascii_hexdigit() || c == '-');
    longest_digits >= 6 || hex
}

/// A class token generated by a build (CSS modules: `name__AGMar`), which changes between
/// releases.
fn generated(token: &str) -> bool {
    token.rsplit_once("__").is_some_and(|(_, suffix)| {
        suffix.len() == 5 && suffix.chars().any(|c| c.is_ascii_uppercase())
    })
}

/// Checks that an expression selects exactly `target` in `tree`'s window `window`.
struct Checker<'a> {
    inspector: &'a RecordedInspector,
    tree: &'a RecordedTree,
    window: usize,
}

impl Checker<'_> {
    fn selects(&self, xpath: &str, target: &str) -> bool {
        let Ok(parsed) = XPath::parse(xpath) else {
            return false;
        };
        let windows = [self.tree.windows[self.window].window.clone()];
        let mut document = Document::new(self.inspector, &windows);
        let Some(context) = document.window(0) else {
            return false;
        };
        match document.select(&parsed, context, &Variables::new()) {
            Ok(nodes) => {
                nodes.len() == 1
                    && matches!(nodes[0], Node::Element(_))
                    && document.id(nodes[0]) == Some(target)
            }
            Err(_) => false,
        }
    }
}

/// The ancestors of an element, nearest first, up to (not including) its window.
fn ancestors(inspector: &RecordedInspector, id: &str) -> Vec<UiElement> {
    let mut out = Vec::new();
    let mut at = id.to_string();
    while let Ok(Some(parent)) = inspector.parent(&at) {
        if parent.role == "Window" && inspector.element(&parent.id).is_none() {
            break;
        }
        at = parent.id.clone();
        out.push(parent);
    }
    out
}

fn tokens(element: &UiElement) -> Vec<String> {
    element
        .class
        .as_deref()
        .unwrap_or_default()
        .split_whitespace()
        .filter(|t| !generated(t))
        .map(String::from)
        .collect()
}

/// The texts the element shows: its name, and the names of its descendant `Text`s.
fn texts(inspector: &RecordedInspector, element: &UiElement) -> Vec<String> {
    let mut out = Vec::new();
    if let Ok(below) = inspector.subtree(&element.id, 8, 200) {
        for (_, e) in below {
            if e.role == "Text" && !e.name.trim().is_empty() && !out.contains(&e.name) {
                out.push(e.name);
            }
        }
    }
    out
}

/// The positional path from the window to the element, which always selects it.
fn path(inspector: &RecordedInspector, target: &UiElement, window_id: &str) -> String {
    let mut chain = ancestors(inspector, &target.id);
    chain.reverse();
    chain.push(target.clone());
    let mut steps = Vec::new();
    let mut parent = window_id.to_string();
    for element in chain {
        let siblings = inspector.children(&parent).unwrap_or_default();
        let same: Vec<&UiElement> = siblings.iter().filter(|s| s.role == element.role).collect();
        let index = same.iter().position(|s| s.id == element.id).unwrap_or(0);
        steps.push(format!("{}[{}]", role_test(&element.role), index + 1));
        parent = element.id.clone();
    }
    steps.join("/")
}

/// Every candidate that selects `target` alone in `tree`, most robust first.
pub fn candidates(tree: &RecordedTree, target: &str) -> Vec<Candidate> {
    let inspector = RecordedInspector::new(tree.clone());
    let Some(element) = inspector.element(target) else {
        return Vec::new();
    };
    // The window the element is in.
    let top = ancestors(&inspector, target)
        .last()
        .map(|e| e.id.clone())
        .unwrap_or_else(|| target.to_string());
    let window = tree
        .windows
        .iter()
        .position(|w| {
            inspector
                .parent(&top)
                .ok()
                .flatten()
                .is_some_and(|p| p.id == w.window.id)
        })
        .unwrap_or(0);
    let checker = Checker {
        inspector: &inspector,
        tree,
        window,
    };
    let role = role_test(&element.role);
    let mut out: Vec<Candidate> = Vec::new();
    let mut push = |xpath: String, how: &str, stable: bool, value: Option<String>| {
        if !out.iter().any(|c| c.xpath == xpath) && checker.selects(&xpath, target) {
            out.push(Candidate {
                xpath,
                how: how.into(),
                stable,
                value,
            });
        }
    };
    if let Some(id) = element.automation_id.as_deref().filter(|i| !i.is_empty())
        && !volatile(id)
    {
        push(
            format!("//{role}[@automation_id={}]", literal(id)),
            "automation_id",
            true,
            None,
        );
    }
    let own = tokens(&element);
    for token in &own {
        push(
            format!("//{role}[has-class(@class, {})]", literal(token)),
            "class",
            true,
            None,
        );
    }
    for (i, a) in own.iter().enumerate() {
        for b in own.iter().skip(i + 1) {
            push(
                format!(
                    "//{role}[has-class(@class, {})][has-class(@class, {})]",
                    literal(a),
                    literal(b)
                ),
                "class",
                true,
                None,
            );
        }
    }
    // Below the nearest ancestor that has a stable id or class of its own.
    for ancestor in ancestors(&inspector, target).iter().take(8) {
        let mut anchors = Vec::new();
        if let Some(id) = ancestor
            .automation_id
            .as_deref()
            .filter(|i| !i.is_empty() && !volatile(i))
        {
            anchors.push(format!(
                "//{}[@automation_id={}]",
                role_test(&ancestor.role),
                literal(id)
            ));
        }
        for token in tokens(ancestor) {
            anchors.push(format!(
                "//{}[has-class(@class, {})]",
                role_test(&ancestor.role),
                literal(&token)
            ));
        }
        for anchor in anchors {
            push(format!("{anchor}//{role}"), "anchored", true, None);
            for token in &own {
                push(
                    format!("{anchor}//{role}[has-class(@class, {})]", literal(token)),
                    "anchored",
                    true,
                    None,
                );
            }
        }
    }
    // By what it shows: the values an argument would carry.
    for text in texts(&inspector, &element) {
        push(
            format!("//{role}[.//Text[@name = {}]]", literal(&text)),
            "text",
            false,
            Some(text.clone()),
        );
        for token in &own {
            push(
                format!(
                    "//{role}[has-class(@class, {})][.//Text[@name = {}]]",
                    literal(token),
                    literal(&text)
                ),
                "text",
                false,
                Some(text.clone()),
            );
        }
    }
    if !element.name.trim().is_empty() && !element.password {
        push(
            format!("//{role}[@name = {}]", literal(&element.name)),
            "name",
            false,
            Some(element.name.clone()),
        );
    }
    let window_id = tree.windows[window].window.id.clone();
    push(path(&inspector, &element, &window_id), "path", true, None);
    // A few of each kind, in the order above, the positional path last.
    let (paths, rest): (Vec<Candidate>, Vec<Candidate>) =
        out.into_iter().partition(|c| c.how == "path");
    let (stable, unstable): (Vec<Candidate>, Vec<Candidate>) =
        rest.into_iter().partition(|c| c.stable);
    stable
        .into_iter()
        .take(6)
        .chain(unstable.into_iter().take(3))
        .chain(paths)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slack() -> RecordedTree {
        serde_json::from_str(include_str!(
            "../../../../examples/desktop/trees/slack.json"
        ))
        .unwrap()
    }

    fn id(tree: &RecordedTree, role: &str, name: &str) -> String {
        RecordedInspector::new(tree.clone())
            .subtree("w-slack", 64, 10_000)
            .unwrap()
            .into_iter()
            .find(|(_, e)| e.role == role && e.name == name)
            .unwrap()
            .1
            .id
    }

    #[test]
    fn a_composer_is_found_by_its_class_first() {
        let tree = slack();
        let composer = id(&tree, "Edit", "Message #general");
        let found = candidates(&tree, &composer);
        assert_eq!(found[0].xpath, "//Edit[has-class(@class, 'ql-editor')]");
        assert!(found.iter().all(|c| {
            let inspector = RecordedInspector::new(tree.clone());
            Checker {
                inspector: &inspector,
                tree: &tree,
                window: 0,
            }
            .selects(&c.xpath, &composer)
        }));
        let name = found.iter().find(|c| c.how == "name").unwrap();
        assert!(!name.stable);
        assert_eq!(name.value.as_deref(), Some("Message #general"));
        let position = |how: &str| found.iter().position(|c| c.how == how).unwrap();
        assert!(
            position("class") < position("name") && position("name") < position("path"),
            "names come after every stable way, and the path last: {found:#?}"
        );
    }

    #[test]
    fn a_channel_is_found_by_its_id_and_by_the_text_an_argument_carries() {
        let tree = slack();
        let random = id(&tree, "TreeItem", "random");
        let found = candidates(&tree, &random);
        assert_eq!(found[0].xpath, "//TreeItem[@automation_id='C03RANDOM33']");
        let text = found.iter().find(|c| c.how == "text").unwrap();
        assert_eq!(text.xpath, "//TreeItem[.//Text[@name = 'random']]");
        assert_eq!(text.value.as_deref(), Some("random"));
        // The class it shares with every channel does not select it alone.
        assert!(
            !found
                .iter()
                .any(|c| c.xpath == "//TreeItem[has-class(@class, 'c-virtual_list__item')]")
        );
    }

    #[test]
    fn generated_ids_and_classes_are_left_out() {
        assert!(volatile("message-list_1790703615.453899"));
        assert!(volatile("3f2a9c0d1e2b4a5c6d7e8f90"));
        assert!(!volatile("C03RANDOM33"));
        assert!(!volatile("sectionHeading-L01C5ABCD"));
        assert!(generated("draggable_tabs_container__AGMar"));
        assert!(!generated("p-channel_sidebar__channel"));
        let tree = slack();
        let message = id(
            &tree,
            "ListItem",
            "Bo Chen: Thanks! I will update the plan. 10:05 AM",
        );
        let found = candidates(&tree, &message);
        assert!(
            found.iter().all(|c| !c.xpath.contains("1790703757")),
            "{found:#?}"
        );
        assert!(!found.is_empty());
        assert_eq!(literal("it's"), "\"it's\"");
        assert_eq!(literal("a'b\"c"), "concat('a', \"'\", 'b\"c')");
    }
}
